package(default_visibility = ["//visibility:public"])

cc_library(
    name = "headers",
    hdrs = [
        "arraylist.h",
        "arraymap.h",
        "ctest.h",
        "defer.h",
        "dev-tools.h",
        "log.h",
        "option-parser.h",
        "utility.h",
        "topset.h",
    ],
    includes = ["./"],
)
